### DISCUSSION TITLE
Why is the ESPBell (un)locking entity a 'switch' and not a 'lock' ?

### DISCUSSION THREAD

**Discussion by jpbaril** [PricelessToolkit/ESPBell-LITE#31] [Q&A] [answered]
Not a problem per se, but I was curious as to why the (un)locking entity was a 'switch' component and not a 'lock' one?
I was going to try this below where I adjusted it to be a lock.
```
lock:
  - platform: gpio
    pin: 5
    id: Lock
    name: "Lock"
    icon: "mdi:door-closed-lock"
    restore_mode: ALWAYS_OFF
    on_unlock:
    - delay: 1000ms 
    - lock.lock: Lock
```
But am I wrong to think I would also have to set 'restore_mode' to 'ALWAYS_ON' since I think the default (and 'true') state of a lock is "locked" ?

Thanks

BTW, I LOVE my ESPBell-lite ! Such a good life improvement!

**Comment by PricelessToolkit** [comment]
"Why is the ESPBell (un)locking entity a 'switch' and not a 'lock' ?"
I can't remember why :)

I think there is no difference. It is lock or switch, it needs to be "ALWAYS_OFF".

When I do the next production batch, I will test and update the lock entity.

Thank you!!

**Comment by PricelessToolkit** [comment, marked as answer]
Added example for lock entity in the instruction

```yaml


switch:
  - platform: gpio
    pin: 5
    id: lock_relay
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 2
    id: led_switch
    inverted: true
    restore_mode: ALWAYS_OFF

  - platform: restart
    name: ${name} restart

lock:
  - platform: template
    name: ${name} Lock
    id: ent_lock
    icon: "mdi:lock"
    optimistic: true
    on_unlock:
      - switch.turn_on: led_switch
      - switch.turn_on: lock_relay
      - delay: 1.5s                    # Change opening time here
      - switch.turn_off: lock_relay
      - switch.turn_off: led_switch
      - lock.lock: ent_lock


```

**Reply by jpbaril** [reply]
With that code I get two issues:

1. ~~The lock action button label is now showing "Verrouiller" (Lock) instead of "Déverrouiller" (Unlock).~~
EDIT: After a first click on the button it now shows "Déverrouiller" (Unlock) as it should.
![Capture d’écran du 2025-06-18 19-24-00](https://github.com/user-attachments/assets/49106f81-b85b-4bc1-baf2-3f263e7dced2)
2. All entities now have the device name duplicated. Eg.:
![Capture d’écran du 2025-06-18 19-24-17](https://github.com/user-attachments/assets/fadfbc05-ee05-4e6a-a70c-1a6fd2b4faca)

**Reply by PricelessToolkit** [reply]
1. It is until you click it once, the reason is "optimistic: true"
2. Delete this part `${name}`

```yaml

lock:
  - platform: template
    name: Lock

```
