### ISSUE TITLE
2024.6.1 Plattform Key missing

### ISSUE THREAD

**Issue by arne182** [PricelessToolkit/ESPBell-LITE#18]
INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/espbell-lite.yaml...
Failed config

ota.unknown: [source /config/esphome/espbell-lite.yaml:26]
  
  'ota' requires a 'platform' key but it was not specified.

**Comment by PricelessToolkit** [comment]
The new ESPhome version requires "- platform: esphome"

like

```yaml
ota:
- platform: esphome
  password: "ABCD"
```

Fixed in config, Thanks!!
