### ISSUE TITLE
Use button entity instead of switch

### ISSUE THREAD

**Issue by PilaScat** [PricelessToolkit/ESPBell-LITE#21]
Is it possibile?

**Comment by PricelessToolkit** [comment]
Control is on pin 5, change the yaml whatever you want

```yaml

switch:

# Door Lock Opener "Momentary Switch" Keeps SSR ON for 1.5s.
  - platform: gpio
    pin: 5
    id: Lock
    name: "Lock"
    icon: "mdi:lock"
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - delay: 1500ms 
    - switch.turn_off: Lock

```

https://esphome.io/components/button/

**Comment by PilaScat** [comment]
What I meant was if it was possible to use a button instead of a switch on Home Assistant, but that's a small thing, if you can't do it easily, never mind

**Comment by PricelessToolkit** [comment]
Not tested. If it works, please let me know.
```yaml

switch:
  - platform: gpio
    pin: 5
    id: UnlockSwitch
    name: "Unlock Switch"
    icon: "mdi:lock"
    restore_mode: ALWAYS_OFF
    internal: true

button:
  - platform: gpio
    id: UnlockButton
    name: "Unlock Button"
    on_press:
      - switch.turn_on: UnlockSwitch
      - delay: 1500ms
      - switch.turn_off: UnlockSwitch


```
