### ISSUE TITLE
Please advise on how to change the lock 'delay'

### ISSUE THREAD

**Issue by MrS4u** [PricelessToolkit/ESPBell-LITE#30]
I added the ESP Lite device through UI, and I can not find the solution to edit the lock 'delay' value (to change it from 1500ms).
Obviously it is not in the configuration.yaml file, and I couldn't find the valid entry in .storage files either.
Please help, thank You!

**Comment by PricelessToolkit** [comment]
it is in "espbell-lite.yam" row 81
https://github.com/PricelessToolkit/ESPBell-LITE/blob/main/Code/ESPHome/espbell-lite.yaml#L81

```yaml

  - platform: gpio
    pin: 5
    id: Lock
    name: "Lock"
    icon: "mdi:lock"
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - delay: 1500ms 
    - switch.turn_off: Lock

```

you can adapt that device after adding it......
